### ISSUE TITLE
Использовать dangerouslySetInnerHTML - очень плохо.

### ISSUE THREAD

**Issue by Fi1osof** [megahertz/react-simple-wysiwyg#1]
Причины две:

1. Безопасность. Критическая проблема. Можно писать теги в том числе с событиями onclick и т.п.
2. Производительность. При таком рендеринге реакт не отслеживает инстансы создаваемых HTML-нод, каждый раз создавая новые при ререндеринге.

**Comment by megahertz** [comment]
@Fi1osof Как вы представляете себе легкий WYSIWYG редактор без этого?

**Comment by Fi1osof** [comment]
@megahertz , сорри за долгий ответ.

Если предполагается использовать редактор только для того, чтобы отредактировать текст, но полученную разметку сохранять и выводить потом через сторонний механизм (например, средствами классической CMS), то да, скорее всего вариантов никаких других. Более того, даже рендеринг на уровне редактора не спасает от инъекций, если серверная часть принимает код полученный как есть, то есть позволяет прислать злоумышленнику что угодно. 
Но если на конечном сайте код выводится все-таки средствами редактора, можно все-таки что-то придумать. К примеру, у меня [вот так делается](https://github.com/prisma-cms/front-editor/blob/master/src/components/App/components/public/Tag/index.js). То есть есть реакт-компонент HtmlTag и через него рендерится каждая HTML-нода. Пока тоже еще версия не стабильная, но во всяком случае позволяет не только не париться на счет безопасности (ее реакт обеспечивает), но и при желании модифицировать вывод. Вот [небольшое видео](https://www.youtube.com/watch?v=UJzgHBV8POc) как работала первая версия.

А вот сегодня я уже боле менее полноценный редактор выкатил: https://prisma-cms.com/topics/contenteditor.html 

Сорри за типа рекламу, но может и вам там там что-нибудь полезное найдется.
К слову, советую тоже oninput заменить на [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). Это позволит более четко отслеживать все изменения. В моей статье про это тоже написано. У вас сейчас не фиксируются изменения, выполняемые программно, в том числе через devTools. Вот записал [проблему](https://www.youtube.com/watch?v=Mvn4vXEg5hg&feature=youtu.be).

**Comment by megahertz** [comment]
@Fi1osof Спасибо за информацию. Вкурсе про MutationObserver. Целенаправленно не стал использовать, чтоб не городить полифилы для старых IE. Мои потребности текущее решение полностью покрывает, а усложнять решение не вижу смысла пока нет особой востребованности библиотеки. В приоритете другие проекты.

**Comment by Fi1osof** [comment]
Не вопрос. Спасибо за ответы.
