### ISSUE TITLE
Getting this error when I reload the page. TypeError: Cannot read properties of undefined (reading 'memo')

### ISSUE THREAD

**Issue by supnim** [megahertz/react-simple-wysiwyg#12]
When I navigate to page it's fine and shows and works but when I reload it, it breaks and throws this error. 

This is my implementation:

TextEditor.tsx:
```
import React, { useState } from "react"
import { DefaultEditor } from "react-simple-wysiwyg"

function TextEditor() {
	const [html, setHtml] = useState("my <b>HTML</b>")

	function onChange(e) {
		setHtml(e.target.value)
	}

	return <DefaultEditor value={html} onChange={onChange} />
}
export default TextEditor

```
post-job.tsx:

```
import TextEditor from "../components/globals/TextEditor"
...
<TextEditor />
...
```

<img width="775" alt="image" src="https://user-images.githubusercontent.com/38427203/184784848-9119ca87-7def-4cb9-addd-b47790e99831.png">

Any help would be wonderful as this WYSIWYG has been the easiest to implement :)

**Comment by megahertz** [comment]
Could you help me to reproduce that? Looks like the UMD module can't be loaded properly in your environment.

**Comment by supnim** [comment]
added you to the repo so you can reproduce the issue :) lmk if I can help in another way

**Comment by megahertz** [comment]
Thank you, I'll take a look a bit later today.

**Comment by supnim** [comment]
wonderful! thanks mate - appreciate it :)

**Comment by megahertz** [comment]
Currently, you can use the following workaround:
`import { DefaultEditor } from "react-simple-wysiwyg/lib/index.js"`
I'll try to make a fix in this week.

**Comment by supnim** [comment]
thanks mate, much appreciated :)

**Comment by supnim** [comment]
I have added you to the repo so you can reproduce it :)

**Comment by megahertz** [comment]
Does v2.1.1 work fine for you without the workaround?
