### ISSUE TITLE
Needs iframe for the preview

### ISSUE THREAD

**Issue by abhibagul** [megahertz/react-simple-wysiwyg#13]
Adding any code inside the HTML editor affects the webpage. Like adding the following code,
`<style>body{background:red}</style>`

**Comment by megahertz** [comment]
I would prefer to keep this library as tiny as possible even if it has such a limitation. Anyway, I'll think about it in the future. Maybe shadow DOM is better for style isolation.

**Comment by megahertz** [comment]
Sorry, I decided not to implement such a feature to keep minimal bundle size.
