### ISSUE TITLE
deprecated method execCommand

### ISSUE THREAD

**Issue by dechamp** [megahertz/react-simple-wysiwyg#17]
https://github.com/megahertz/react-simple-wysiwyg/blob/0deef4f7e2d1ce54d2eeaa5239aa8e91b14d40c8/src/toolbar/buttons.tsx#L71

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by megahertz** [comment]
I know, but there's no alternative yet and I don't think it will be removed from browsers in the next 5-10 years.
