### ISSUE TITLE
Undo/redo linked between multiple editors

### ISSUE THREAD

**Issue by duhmojo** [megahertz/react-simple-wysiwyg#24]
Hey. I noticed that the undo/redo is linked between multiple instances of the editor. I'm using it in a multi-field page and if I edit one, then the other, and click into the 1st one again, undo will undo the other (not the one in focus) and if I undo enough it'll undo changes in the 1st.

I expect its some shared reference. If you have a suggestion on how to separate this it would be great. BTW I'm using your awesome simple editor for a non-public function, so I'm not expecting it to be perfect, but it is light weight and works perfectly well enough in more cases. Thanks again.

**Comment by megahertz** [comment]
Thank you for the report, fixed

**Comment by duhmojo** [comment]
Amazing. Thanks!
