### ISSUE TITLE
Fails to install with Yarn

### ISSUE THREAD

**Issue by Daronspence** [megahertz/react-simple-wysiwyg#3]
Hello, 

If I try to install the package with yarn on node 15, it fails with this error.

```sh
error /Users/daron/Sites/cooking-school/node_modules/react-simple-wysiwyg: Command failed.
Exit code: 254
Command: npm install --prefix examples/typescript
Arguments: 
Directory: /Users/daron/Sites/cooking-school/node_modules/react-simple-wysiwyg
Output:
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /Users/daron/Sites/cooking-school/node_modules/react-simple-wysiwyg/examples
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/daron/Sites/cooking-school/node_modules/react-simple-wysiwyg/examples'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

It appears to be something with the `examples` directory which I noticed was not included with the NPM version. If I use the github repo:
```
yarn add https://github.com/megahertz/react-simple-wysiwyg
```
the package installs correctly.

Cheers

**Comment by Daronspence** [comment]
Actually, I couldn't get it to work with the github raw version either. I think I would need to build it first... I'm pretty new to react/JS (more of a backend guy) so any help is appreciated!

**Comment by megahertz** [comment]
Thank you for the report, will be fixed soon
