### ISSUE TITLE
Can't import named export 'DefaultEditor' from non-EcmaScript module during Server-Side Rendering (SSR)

### ISSUE THREAD

**Issue by GanonForce** [megahertz/react-simple-wysiwyg#30]
Hello,

I'm facing an issue when attempting to import the named export DefaultEditor from the react-simple-wysiwyg module during Server-Side Rendering (SSR). The specific error message I receive is: "Can't import the named export 'DefaultEditor' from non-EcmaScript module (only default export is available)".

Here's my current import statement where the error surfaces:

```import { DefaultEditor } from 'react-simple-wysiwyg';```

![image](https://github.com/megahertz/react-simple-wysiwyg/assets/43139652/784071f6-416f-40c0-b17b-ce5b97f9856b)

Also, I'm not trying to render the component itself on the server side, rendering it using the "!isFirstRender" condition

I would appreciate any guidance or updates to resolve this issue.

Best Regards, Alexandr

**Comment by megahertz** [comment]
It depends on the bundler and its configuration. As a quick workaround, you can try importing a commonjs module from 'react-simple-wysiwyg/lib/index.cjs.js'

**Comment by GanonForce** [comment]
Unfortunately the error remains if I import from 'react-simple-wysiwyg/lib/index.cjs.js'

**Comment by megahertz** [comment]
If you provide more information about your bundler I can investigate the issue when I have enough time. Looks like the only workaround now is using default export.

**Comment by jakkub21** [comment]
I'm facing similar issue. I have react app created with CRA: https://create-react-app.dev/

**Comment by megahertz** [comment]
@GanonForce @jakkub21 could you try react-simple-wysiwyg@3.0.0 ?

**Comment by GanonForce** [comment]
@megahertz, yes I'll check it tomorrow and write back to you.

**Comment by megahertz** [comment]
@GanonForce which react version do you use?

**Comment by GanonForce** [comment]
@megahertz i use react 18.2.0

**Comment by jakkub21** [comment]
@megahertz im using react 16.13.1, sorry for the late response.

i also implemented your library with current version 3.0.0 as @GanonForce mentioned above by importing: 
```jsx
import { DefaultEditor } from 'react-simple-wysiwyg/lib/index.cjs
```

**Comment by megahertz** [comment]
I'm going to solve the issue in the next two weeks.

**Comment by megahertz** [comment]
@GanonForce @jakkub21 could you try react-simple-wysiwyg@3.0.1?

**Comment by jakkub21** [comment]
@megahertz i just tested it on React 16.13.1 and by simply importing components from your library its seems to work.

Example:
```js
import React, { useState } from 'react';
import Editor from 'react-simple-wysiwyg';

// jsx
const PositionForm = () => {
   const [form, setForm] = useState({
      title: "",
      description: ""
   })
   
   return (
       <form>
           <input value={form.title} onChange={(e, {value}) => setForm(prev => ({...prev, title: value}))}/>
           <Editor value={form.description} onChange={(e, { value }) => setForm({
                  ...form,
                  description: value
            })} />
       </form>
   )
}
```

**Comment by megahertz** [comment]
Thank you @jakkub21. I'm going to make a release in 2 weeks

**Comment by megahertz** [comment]
published
