### ISSUE TITLE
Numbered and Bullet lists are not working

### ISSUE THREAD

**Issue by T3chnoMaciej** [megahertz/react-simple-wysiwyg#31]
Hi!
I'm using this software in a Next.js 13.5.6 app, in a client component. Every function works fine except for lists , that dont'
Here's my code:
`
"use client";
import { useState } from 'react';
import {  BtnBold, BtnItalic, Editor, EditorProvider, Toolbar, BtnNumberedList, BtnBulletList, BtnUnderline} from 'react-simple-wysiwyg';

export default function NotesComponent() {
    const [notesValue, setNotesValue] = useState('Start typing...');

    function onChangeEditor(e) {
        setNotesValue(e.target.value);
    }

    return(
        <EditorProvider>
            <Editor value={notesValue} onChange={onChangeEditor} >
                <Toolbar>
                    <BtnBold />
                    <BtnUnderline />
                    <BtnItalic />
                    <div className="rsw-separator" />
                    <BtnNumberedList />
                    <BtnBulletList />
                </Toolbar>
            </Editor>
        </EditorProvider>
    )
}

`

**Comment by megahertz** [comment]
It works fine in my local environment with Chrome 118.0.5993.88. Which browser do you use?

**Comment by T3chnoMaciej** [comment]
Hi, thanks for the reply. I use Chrome 116 on macOS. I'll check after update.

**Comment by T3chnoMaciej** [comment]
Hi, 

Sorry for the late reply, I was short on time lately. Here you go: [https://github.com/T3chnoMaciej/recreate-react-wysiwyg-error](I created a simple project with this problem in a repo) . I hope it helps and we can eliminate this bug. Tested on 2 more browsers, same effect. 

Cheers,
M

**Comment by megahertz** [comment]
Thank you. I'll take a look in the beginning of the next week.

**Comment by megahertz** [comment]
These buttons work fine, but the global style in next.js/tailwindcss prevents the list from being displayed correctly.

```css
/* /_next/static/css/app/layout.css?v=1702231607245 */
ol, ul, menu {
    list-style: none;
    margin: 0;
    padding: 0;
}
```

**Comment by T3chnoMaciej** [comment]
Thank you for your time, I will debug in my code
