### ISSUE TITLE
Some options are working some are not.

### ISSUE THREAD

**Issue by Nigro69** [megahertz/react-simple-wysiwyg#39]
### Options like undo/redo/bold/italic/underline/strike through/  they are working fine but after that all the options either misbehave or doesn't work.

https://github.com/megahertz/react-simple-wysiwyg/assets/112351758/c88a5f50-596e-4851-9f04-94502e73a4cd

```
import { useState } from 'react';
import Editor from 'react-simple-wysiwyg';

function App() {
  const [html, setHtml] = useState('my <b>HTML</b>');
  
  function onChange(e) {
    setHtml(e.target.value);
  }

  return (
    <Editor value={html} onChange={onChange} />
  );
}
```
I just want simple editor and yours is perfect but this issue is frustrating.

Please look into the issue.
Thanks in advance

**Comment by megahertz** [comment]
Most probably that's the same https://github.com/megahertz/react-simple-wysiwyg/issues/31

**Comment by yash-3010** [comment]
Okay got it..
Thanks for you time.

**Comment by Nigro69** [comment]
Okay got it.
Thanks for your time,
