### ISSUE TITLE
Links display with Chakra UI

### ISSUE THREAD

**Issue by PaulMonnery** [megahertz/react-simple-wysiwyg#44]
Hello,

I am trying to use the package in a react/ts/chakra project, but it fails to render correctly some HTML elements like links and lists when wrapped in the ChakraProvider.

[Here is a sandbox](https://codesandbox.io/p/sandbox/react-simple-wysiwyg-chakra-s4r2f8?file=%2Fsrc%2Findex.tsx%3A14%2C1) to check. If you comment the ChakraProvider, the formatting becomes correct.

It is probably related to #31, is there any global workaround?

**Comment by megahertz** [comment]
Yes, that's the same issue. You need to redefine styles for links and lists inside the `rsw-ce` container.

**Comment by Hombre2014** [comment]
Hi, @megahertz I tried to redefine the styles in my global.css (it is a Next.js with TailwindCSS and TypeScript project) but it does not work. I added:

`
@layer base {
  .rsw-ce ul {
    @apply list-disc;
    @apply pl-8;
  }

  .rsw-ce ol {
    @apply list-decimal;
    @apply pl-8;
  }
}
`

What am I doing wrong?
