### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by yaxue1123** [megahertz/react-simple-wysiwyg#52]
Hi Alexy, thank you for this library! 

One minor request, could you please make the link to open a new tab by default? Or give the option to set the `target` attribute. Thanks!

**Comment by megahertz** [comment]
You can add a handler like this:
```
<Editor
  onClick={(e) => {
    if (e.target.tagName === 'A') {
      window.open(e.target.href, '_blank');
      e.preventDefault();
    }
  }}
/>
```
