### ISSUE TITLE
Bug with the generated HTML as soon as you start typing

### ISSUE THREAD

**Issue by alessiofnes** [megahertz/react-simple-wysiwyg#56]
Hi @megahertz,
as you can see on your demo page https://megahertz.github.io/react-simple-wysiwyg/ when you start typing the source code doesn't wrap your text with a <div> tag and this may cause viewing problems sometimes. With the next line break it add <div> correctly. Also if you add a line break and then delete it, it inserts the <div> in the right way.

Do you think it is possible to fix this issue?

Cheers.

**Comment by megahertz** [comment]
That's default contenteditable behavior. Could you describe in detail which problems it can cause?

**Comment by alessiofnes** [comment]
If I use the editor to create a simple HTML snippet that must be used into an HTML email body I need to have a solid and verbose HTML (with some inline style for a good cross-platform readability).  If some text miss the HTML tag I can't apply the correct inline style.

**Comment by megahertz** [comment]
I have no plans to modify the HTML generated by the browser. Otherwise, this library won't stay tiny and lightweight anymore.  If you need to receive more predictable HTML, I think you need a more powerful editor.
