### ISSUE TITLE
When using placeholder two clicks are needed to focus the input

### ISSUE THREAD

**Issue by Han1s** [megahertz/react-simple-wysiwyg#57]
HI megahertz, thank you for a great library.

There is a small bug I found
- reproducible on chromium, firefox seems to not have this issue
- only happens when user clicks on the placeholder text (not happening when you click anywhere else in the input field or if you are not using placeholder text)

Impact: The first click will not focus the input, only remove the placeholder, the second click then focuses the input.
Expected: The first click should handle both, remove the placeholder and focus the input, so user can start typing right away.

If you ever have time to check on it, that would be cool.

Thanks a lot for your time

**Comment by megahertz** [comment]
Should be fixed in 3.1.3
