### ISSUE TITLE
Placeholder for editor

### ISSUE THREAD

**Issue by urlGuney** [megahertz/react-simple-wysiwyg#6]
I exactly implemented the editor like in the documents. Which it works fine. But I wonder that can i add placeholder to my editor. Because I tried to add placeholder like it's an input field but it didn't work.

**Comment by megahertz** [comment]
I'll think about it in the next version. I think it'll be ready in March.

**Comment by megahertz** [comment]
Implemented in 2.0.0-alpha.4
